coverage:
  status:
    project:
      default:
        target: auto
        threshold: 100%
        paths: 
          - "src"
        branches: 
          - main
        if_ci_failed: ignore
        informational: false
        only_pulls: false
