name: Rust

on: [push]
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --package rust_socketio --lib -- socketio::packet::test --verbose
    - name: Linting
      run: cargo clippy --verbose
    - name: Check formatting
      run: cargo fmt --all -- --check
