on: [pull_request]

name: benchmark engine.io
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: boa-dev/criterion-compare-action@v3.0.0
        with:
          cwd: "engineio"
          branchName: ${{ github.base_ref }}
